stages:
  - sanity
  - build
  
sanity-check:
  stage: sanity
  script:
    - export
  tags:
    - grunner4wetry

build-broadcom:
  stage: build
  script:
    - make init
    - make configure PLATFORM=broadcom
    - make target/sonic-broadcom.bin
    - sudo chown -R gitlab-runner:gitlab-runner fsroot/var    
  tags:
    - grunner4wetry
