stages:
  - sanity
  - build
  
sanity-check:
  stage: sanity
  script:
    - export
  tags:
    - redding4wetry

build-broadcom-kdump:
  stage: build
  script:
    - make init
    - make configure PLATFORM=broadcom
    - make SONIC_ENABLE_KDUMP=y target/sonic-broadcom.bin
    - sudo chown -R gitlab-runner:gitlab-runner fsroot/*
    - mv target ~/saved/target.$$
  tags:
    - redding4wetry
