stages:
  - sanity
  - build
  - test

sanity-check:
  stage: sanity
  script:
    - export
  tags:
    - redding4wetry

build-broadcom:
  stage: build
  script:
    - make init
    - make configure PLATFORM=broadcom
    - make target/sonic-broadcom.bin
    - sudo chown -R ${LOGNAME}:${LOGNAME} fsroot/*
    - mv target ~/workspace/res/sonic/pkgs/gitlab-runner/target.${CI_JOB_ID}
    - pushd ~/workspace/res/sonic/pkgs/gitlab-runner
    - ln -sfn target.${CI_JOB_ID} target.cur
    - popd
  tags:
    - redding4wetry

build-broadcom-kdump:
  stage: build
  script:
    - make init
    - make configure PLATFORM=broadcom
    - make SONIC_ENABLE_KDUMP=y target/sonic-broadcom.bin
    - sudo chown -R ${LOGNAME}:${LOGNAME} fsroot/*
    - mv target ~/workspace/res/sonic/pkgs/gitlab-runner/target.kdump.${CI_JOB_ID}
    - pushd ~/workspace/res/sonic/pkgs/gitlab-runner
    - ln -sfn target.kdump.${CI_JOB_ID} target.cur.kdump
    - popd
  tags:
    - redding4wetry
  only:

test:
  stage: test
  script:
    - git clone git@gitlab.com:gl4sun/integration.git
    - pushd integration
    - checkout ali
    - pushd pipeline/kdump/driver
    - kdump.sh /tmp/stop /tmp/kdump.log reminder4sun@hotmail.com ~/workspace/res/sonic/pkgs/gitlab-runner/target.cur
    - popd
  tags:
   - redding4wetry
