stages:
  - sanity
  - default-build
  - test

sanity-check:
  stage: sanity
  script:
    - export
  tags:
    - redding4wetry

build-arm:
  stage: default-build
  script:
    - make init
    - git clone git@github.com:Marvell-switching/sonic-M0-scripts.git
    - bash -x sonic-M0-scripts/sonic_apply_openPRs_mvl.sh
    - sed -i "s/\(SONIC_CONFIG_BUILD_JOBS\)\(.*\)/\1 = 8/g" rules/config      
    - make configure PLATFORM=marvell-armhf PLATFORM_ARCH=armhf
    - make target/sonic-marvell-armhf.bin
    - sudo chown -R ${LOGNAME}:${LOGNAME} fsroot/*
    - sudo chown -R ${LOGNAME}:${LOGNAME} dockerfs/*
    - mv target ~/workspace/res/sonic/pkgs/gitlab-runner/target.${CI_JOB_ID}
    - pushd ~/workspace/res/sonic/pkgs/gitlab-runner
    - ln -sfn target.${CI_JOB_ID} target.cur
    - popd
  tags:
    - redding4wetry

test:
  stage: test
  script:
    - git clone git@gitlab.com:gl4sun/integration.git
    - pushd integration
    - git checkout ali
    - pushd pipeline/kdump/driver
    - ./kdump.sh /tmp/stop /tmp/kdump.log reminder4sun@hotmail.com ~/workspace/res/sonic/pkgs/gitlab-runner/target.cur
    - popd
  tags:
   - redding4wetry
  only:
   - whatever
